/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RestauranteMejorado;

import javax.swing.JTextArea;

/**
 *
 * @author Administrador
 */
public class Restaurante extends javax.swing.JFrame {

    /**
     * Creates new form Restaurante
     */
    public Restaurante() {
        initComponents();
        setLocationRelativeTo(null);//centra la ventana en la patalla
        setTitle("Resturante masmejor");
        setVisible(true);
        
    }

    int cantidadHamburguesa=0;
    int cantidadCerveza=0;
    int cantidadSalat=0;
    int cantidadSandwich=0;
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        FondoPanel = new javax.swing.JPanel();
        HamburguesaButton = new javax.swing.JButton();
        CervezaButton = new javax.swing.JButton();
        ChanwisButton = new javax.swing.JButton();
        SalatButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        LimpiarButton = new javax.swing.JButton();
        AceptarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SubtotalTextField = new javax.swing.JTextField();
        MenosHamburButton = new javax.swing.JButton();
        MenosCerveButton = new javax.swing.JButton();
        MenosSandButton = new javax.swing.JButton();
        MenosSalatButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ContenidoTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ImpuestosTextField1 = new javax.swing.JTextField();

        jButton3.setText("Salir");
        jButton3.setPreferredSize(new java.awt.Dimension(72, 22));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HamburguesaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RestauranteMejorado/Burguer.jpg"))); // NOI18N
        HamburguesaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HamburguesaButtonActionPerformed(evt);
            }
        });

        CervezaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RestauranteMejorado/Cerveza.jpg"))); // NOI18N
        CervezaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CervezaButtonActionPerformed(evt);
            }
        });

        ChanwisButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RestauranteMejorado/Sandwich.jpg"))); // NOI18N
        ChanwisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChanwisButtonActionPerformed(evt);
            }
        });

        SalatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RestauranteMejorado/ensaladaDibujos.png"))); // NOI18N
        SalatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalatButtonActionPerformed(evt);
            }
        });

        SalirButton.setText("Salir");
        SalirButton.setPreferredSize(new java.awt.Dimension(72, 22));
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        LimpiarButton.setText("Limpiar");
        LimpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarButtonActionPerformed(evt);
            }
        });

        AceptarButton.setText("Aceptar");
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Costo sin Impuestos");

        jLabel2.setText("SubTotal");

        SubtotalTextField.setMinimumSize(new java.awt.Dimension(161, 22));
        SubtotalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtotalTextFieldActionPerformed(evt);
            }
        });

        MenosHamburButton.setText("-1");

        MenosCerveButton.setText("-1");

        MenosSandButton.setText("-1");

        MenosSalatButton.setText("-1");

        ContenidoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Hamburguesa", null,  new Double(15.0)},
                {"Ensalada", null,  new Double(7.0)},
                {"Sandwich", null,  new Double(3.0)},
                {"Cerveza", null,  new Double(1.0)}
            },
            new String [] {
                "Alimento", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ContenidoTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ContenidoTable.setPreferredSize(new java.awt.Dimension(265, 100));
        jScrollPane2.setViewportView(ContenidoTable);

        jLabel3.setText("Impuestos");

        ImpuestosTextField1.setMinimumSize(new java.awt.Dimension(161, 22));

        javax.swing.GroupLayout FondoPanelLayout = new javax.swing.GroupLayout(FondoPanel);
        FondoPanel.setLayout(FondoPanelLayout);
        FondoPanelLayout.setHorizontalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ChanwisButton))
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(MenosSandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SalatButton)
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addComponent(MenosSalatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(MenosHamburButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HamburguesaButton))
                        .addGap(45, 45, 45)
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CervezaButton)
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(MenosCerveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addComponent(AceptarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LimpiarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(FondoPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SubtotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(FondoPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(ImpuestosTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 89, Short.MAX_VALUE))
        );
        FondoPanelLayout.setVerticalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addComponent(HamburguesaButton)
                                .addGap(5, 5, 5)
                                .addComponent(MenosHamburButton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addComponent(CervezaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(MenosCerveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addComponent(ChanwisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MenosSandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SalatButton)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoPanelLayout.createSequentialGroup()
                                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(SubtotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(ImpuestosTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MenosSalatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AceptarButton)
                                    .addComponent(LimpiarButton)
                                    .addComponent(SalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void LimpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiarButtonActionPerformed

    private void HamburguesaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HamburguesaButtonActionPerformed
        cantidadHamburguesa++;
        ContenidoTable.setValueAt(cantidadHamburguesa, 0, 1);             
       
    }//GEN-LAST:event_HamburguesaButtonActionPerformed

    private void CervezaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CervezaButtonActionPerformed
        cantidadCerveza++;
        ContenidoTable.setValueAt(cantidadCerveza, 3, 1);
       
    }//GEN-LAST:event_CervezaButtonActionPerformed

    private void ChanwisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChanwisButtonActionPerformed
        cantidadSandwich++;
        ContenidoTable.setValueAt(cantidadSandwich, 2, 1);
       
    }//GEN-LAST:event_ChanwisButtonActionPerformed

    private void SalatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalatButtonActionPerformed
        cantidadSalat++;
        ContenidoTable.setValueAt(cantidadSalat, 1, 1);
        
    }//GEN-LAST:event_SalatButtonActionPerformed

    private void SubtotalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtotalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubtotalTextFieldActionPerformed

    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        calcularSubtotal();
    }//GEN-LAST:event_AceptarButtonActionPerformed

  
     
     public void calcularSubtotal() {
        double hamburguesaPrecio= PrecioTotal(0,0);//hamburguesa
        double salatPrecio= PrecioTotal(1,1);//salat
        double chanwisPrecio= PrecioTotal(2,2);//chanwis
        double cervezaPrecio= PrecioTotal(3,3);//cerveza
        
        
        double sumatotal=hamburguesaPrecio + salatPrecio + chanwisPrecio + cervezaPrecio;
        SubtotalTextField.setText(String.valueOf(sumatotal));
      }
     
    public double PrecioTotal(int cantidadPosicion, int precioPosicion) {//fila, columna
        int cantidad= (int) ContenidoTable.getValueAt(cantidadPosicion, 1);
        double precio = (double) ContenidoTable.getValueAt(precioPosicion, 2);
        if(cantidad>0){
            return cantidad * precio;
        }else{
            return 1;
        }
        
            
    }
    
    
      
    
     

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private javax.swing.JButton CervezaButton;
    private javax.swing.JButton ChanwisButton;
    private javax.swing.JTable ContenidoTable;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JButton HamburguesaButton;
    private javax.swing.JTextField ImpuestosTextField1;
    private javax.swing.JButton LimpiarButton;
    private javax.swing.JButton MenosCerveButton;
    private javax.swing.JButton MenosHamburButton;
    private javax.swing.JButton MenosSalatButton;
    private javax.swing.JButton MenosSandButton;
    private javax.swing.JButton SalatButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JTextField SubtotalTextField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
